mamba:
  n_blocks: 4
  state_dim: 16
  conv_dim: 4
  expand: 2

device: "cuda"
lr: 1e-4

T: 10
obs_dim: 26      # robot(4) + goal(2) + 3 pedestrians * 4 = 18维
action_dim: 2
max_steps: 500

n_peds: 5
scene_size: 8
robot_radius: 0.3
comfort_radius: 0.5
ped_radius: 0.3
dt: 0.1
robot_max_speed: 1.5
ped_max_speed: 0.4
goal_radius: 0.5

gamma: 0.99

reward:
  success_reward: 10.0
  collision_penalty: -1.0
  timeout_penalty: -0.5
  discomfort_dist: 0.6
  discomfort_penalty_factor: 0.2
  step_penalty: -0.01
  dist_reward_factor: 0.2


